spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pharmacyposdb
    username: root
    password: test$123
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: PosPharmacy
  jpa:
    hibernate:
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
server:
  port: 8090
